language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t praseela/docker-frontend -f Dockerfile.dev .

script:
  - docker run praseela/docker-frontend npm run test -- --coverage