language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t praseela/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true praseela/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-082683392979"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"